volumes:
  n8n_storage:
  postgres_storage:
  qdrant_storage:
  n8n_mcp_storage:

networks:
  demo:

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ['demo']
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
    - N8N_HOST=${N8N_HOST}
    - WEBHOOK_URL=${WEBHOOK_URL}
    - N8N_PROTOCOL=${N8N_PROTOCOL}
  env_file:
    - path: .env
      required: true

services:
  postgres:
    image: postgres:16-alpine
    hostname: postgres
    networks: ['demo']
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    <<: *service-n8n
    hostname: n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    container_name: qdrant
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage

  ngrok:
    image: ngrok/ngrok:latest
    command: ["http", "n8n:5678", "--log=stdout"]
    ports:
      - 4040:4040  # Optional, for ngrok web UI to inspect traffic
    networks:
      - demo
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}  # set this in your .env

  n8n-mcp:
    image: ghcr.io/czlonkowski/n8n-mcp:latest
    hostname: n8n-mcp
    container_name: n8n-mcp
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes:
      - n8n_mcp_storage:/app/data
    environment:
      - N8N_MCP_SERVER_PORT=3000
      - N8N_MCP_SERVER_HOST=0.0.0.0
    depends_on:
      - n8n
